name: habitos_app_smart_tv
description: "HabitFlow — Dashboard para Android TV."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.16.0
  flutter_riverpod: ^3.3.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
